### ISSUE TITLE
firehose-to-syslog : Exception occurred! Message: Firehose Error! Details: Error dialing traffic controller server: Service Unavailable

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry-community/firehose-to-syslog#100]
We are trying to use firehose-to-syslog: https://github.com/cloudfoundry-community/firehose-to-syslog.
After pushing the application, we are getting following error:
Error message:
2016-06-17T15:24:17.000+00:00 [APP] ERR [2016-06-17 15:24:17.125829248 +0000 UTC] Exception occurred! Message: Firehose Error! Details: Error dialing traffic controller server: Service Unavailable.
2016-06-17T15:24:17.000+00:00 [APP] ERR Please ask your Cloud Foundry Operator to check the platform configuration (traffic controller is wss://doppler.devcloudwest.xxxxx.com:443).
I got the Doppler server endpoint from system info.
System info:
# cf curl /v2/info
{
........
"routing_endpoint": "https://api.devcloudwest.xxxxx.com/routing",
"logging_endpoint": "wss://loggregator.devcloudwest.xxxxx.com:443",
"doppler_logging_endpoint": "wss://doppler.devcloudwest.xxxxx.com:443",
"user": "20717dac-6773-4e66-9568-862b3df679be"
}
The env variables in manifest.yml is as follows:

API_ENDPOINT: https://api.devcloudwest.xxxxx.com
DOPPLER_ENDPOINT: wss://doppler.devcloudwest.xxxxx.com:443
......
SYSLOG_ENDPOINT: <my-syslog-url>:1414

As I was not sure if I should put inside o: system s:app-manager, I have put the firehose-to-syslog app in a custom org/space.
Appreciate your quick help!

**Comment by shinji62** [comment]
Which options are you using when you start the nozzle  ??

Thanks

**Comment by ichandan16** [comment]
Thank you for your help. I am happy to share you that, have worked firehose-to-syslog out. It should be treated as any other app in any Org/Space. One thing that was troubling me was http_proxy. I have removed it from the manifest.yml and its working.
For app logs , EVENTS: LogMessage
for Sys-logs, EVENTS: ValueMetric,Error,ContainerMetric

**Comment by shinji62** [comment]
Nice !
