### ISSUE TITLE
Generate subscription id or require one to be set

### ISSUE THREAD

**Issue by mrbuk** [cloudfoundry-community/firehose-to-syslog#101]
__Enhancement / Feature request__

As the subscription id is not required and defaults to 'firehose' it could happen that messages are being load balanced _accidentally_ (different run execute `firehose-to-syslog` with different endpoints). 

So it might be worth considering to:

* use a UUID for the subscription id if nothing is provided

or 

 * make the subscription id a required field without a default value.

**Comment by shinji62** [comment]
You have to know what you are doing. UUID is not good idea, the main idea is scaling out.
I want the firehose to be simple as possible so I was thinking about not touching that.


If I got more request I will think about.

**Comment by mrbuk** [comment]
First of all thanks a lot for the quick answer.

> You have to know what you are doing. 
Basically I agree with you but still there are situations where it is not always possible to have control over everything.

> UUID is not good idea, the main idea is scaling out.
Is there an issue with UUID not being able to scale? So in the case when __no__ subscription id will be provided you are right, you cannot scale out anymore because a random subscription id will be used. So if you want to scale out you __need__ to provide a subscription id. 

At the moment the behaviour is the opposite if you don't provide a subscription id a static one is assumed and this leads in my point of view to the situation that you may scale out in cases when you don't know that you scale out.

So what I am trying to propose is a way of making sure that no accidental spin up of a firehose-to-syslog instance will lead to maybe __loosing__ data. For sure that means for the use case of scaling out that you have to provide a subscription id.
