### ISSUE TITLE
Load balance syslog output

### ISSUE THREAD

**Issue by pgullette** [cloudfoundry-community/firehose-to-syslog#103]
We are pushing data into a load balancer currently from CF, but since only a single TCP connection is made from the firehose to the load balancer, the lb doesn't get a chance to change which server is used unless a new TCP connection is established. I've been looking at how best to solve this issue, and my options so far seem to be to try and implement something on the lb side where I cause the TCP connection to get reset after some timeout. The other options seem to be to implement some changes to this code where I either cause the connection to terminate, and then reestablish itself after some duration, or completely bypass the load balancer and instead have this application choose from a group of possible endpoints for the syslog output.

If anyone else has tried to solve something like this, and they were able to do it at the network load balancer side, that would be great. If however, I need to make changes to this code, I want to avoid any kind of data loss from the firehose as well as prevent any kind of performance bottlenecks. I haven't dug very deep into the code to determine where the best place to make the change would be, but I figured I might as well put the questions out to this group to see if I got any feedback.

Thanks for any help you can provide.

**Comment by shinji62** [comment]
Oh, 
I got the same question today.

Just one question about your setup


CF --> firehose-to-syslog --> LB --> syslog-endpoint

or 

CF--> LB --> firehose-to-syslog --> syslog-endpoint

Thanks

**Comment by pgullette** [comment]
CF --> firehose-to-syslog --> LB --> syslog-endpoint
