### ISSUE TITLE
Cannot run amd64 binary

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry-community/firehose-to-syslog#105]
Hi!
I faced issue with running amd64 binary for firehose-to-syslog. 
```
$ ./firehose-to-syslog_linux_amd64
-bash: ./firehose-to-syslog_linux_amd64: No such file or directory
```
In the same time i can execute 386 version:
```
$ ./firehose-to-syslog_linux_386
firehose-to-syslog_linux_386: error: required flag --api-endpoint not provided, try --help
```
I believe that this can be some issue with CI pipeline, because amd64 versions below 1.4.0 version works for me without any issues.

**Comment by Infra-Red** [comment]
```
# ldd firehose-to-syslog_linux_amd64
	linux-vdso.so.1 =>  (0x00007ffc4e9f1000)
	libc.musl-x86_64.so.1 => not found
```
Fixed by installing `musl` library using `apt install musl` which is not present on ubuntu stemcells.
```
$ ./firehose-to-syslog_linux_amd64
firehose-to-syslog_linux_amd64: error: required flag --api-endpoint not provided, try --help
```

**Comment by Infra-Red** [comment]
I am sorry for reopening this issue, i just want to clarify that my findings are correct and this is expected behaviour of `firehose-to-syslog_linux_amd64` binary.
Thanks!

**Comment by shinji62** [comment]
I know this issue, I use alpine linux to compile firehose-to-syslog which do not use libc but muslc.

So yes amd64 is working for muslc distribution.

Anyway I will check.
thanks

**Comment by shinji62** [comment]
Seems most of the people use ubuntu / libc based stemcell.
I will change the pipeline.

Thanks

**Comment by shinji62** [comment]
Please reopen if 1.7.2 do not work.
