### ISSUE TITLE
Need feature to split message size sent to syslog

### ISSUE THREAD

**Issue by shouah** [cloudfoundry-community/firehose-to-syslog#111]
With recent Pivotal Cloud Foundry releases, the message size went from 4k to 60k. Unfortunately our syslog server have a hard-coded size setting at 10k, therefore we can't consume messages larger than ~9.5k.
We need the ability to specify a maximum message size and have the firehose-to-syslog application manually split the message and send those chunk to the syslog server. Without this feature, our syslog server just truncate and discard the content exceeding its message size.

Something like SYSLOG_MAXMSGSIZE setting.

**Comment by shinji62** [comment]
Hi,

How about changing your syslog server configuration ?
Adding this kind of feature could lead to decrease the perf of firehose-to-syslog.

Thanks

**Comment by shouah** [comment]
You may have missed the "server have a hard-coded size setting" part. The vendor, VMware, does not allow its syslog server product, VMware Log Insight, to have its syslog message size changed.

This somewhat puzzling given that both VMware and Pivotal are EMC Federation companies and both are involved behind the scene on Cloud Foundry but don't seem to get this part in agreement.

Would help if this feature was developed in such a way that the workflow would only be invoked if the setting is defined? in another word, same code path and hence performance if the setting is not defined, and if defined then the new code path which may have some slower performance?

Slower performance is preferable to losing data.
