### ISSUE TITLE
Error event "source" field renaming

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/firehose-to-syslog#114]
Hi guys,

I'm a bit confused with this field naming (see https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/events/events.go#L264):

`"delta": errorEvent.GetSource()`

Why do you call "source" field a "delta"? Is it a mistake?

Regards,
Hanna

**Comment by shinji62** [comment]
Agree, that's a bug.
I will review all dropsonde protocol filed soon.

No need to to open a PR.
I am rewritting the nozzle a little bit.

**Comment by hannayurkevich** [comment]
Thank you!

**Comment by shinji62** [comment]
Please use 2.X.X version should be fixed

**Comment by hannayurkevich** [comment]
Thank you a lot! v2.0.0 works well.
