### ISSUE TITLE
Use String values instead of numeric codes in Http* events

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/firehose-to-syslog#115]
Hi,

It looks like Http* events use numeric values for fields `method` and `peer_type` instead of their translated String values.

I beleive that fields

`"method":            httpStart.GetMethod(),` and 
`"peer_type":         httpStart.GetPeerType(),` 

should be set as 

`"method":            httpStart.GetMethod().String(),` and 
`"peer_type":         httpStart.GetPeerType().String(),` 

for all Http* events (HttpStart, HttpStop, HttpStartStop). Similar to LogMessage.message_type field.

**Comment by shinji62** [comment]
Will put this on the v2.
Thanks

**Comment by shinji62** [comment]
Please use 2.X.X version
