### ISSUE TITLE
Field collision with 'index' keyword in Splunk

### ISSUE THREAD

**Issue by mdalley** [cloudfoundry-community/firehose-to-syslog#119]
'index' field was introduced in 1.7.0.
ref: https://github.com/cloudfoundry-community/firehose-to-syslog/commit/58c09896bec6d17653e2e27e9b050845ac891358

1.7.0+ firehose-to-syslog event messages are annotated with a field name of 'index' which conflicts with Splunk's use of 'index' keyword to specify database indices in search queries.
Can we change the 'index' field name in the AnnotateWithEnveloppeData function to something like 'job_index'?

**Comment by shinji62** [comment]
This is a specificity of splunk.
Firehose-to-syslog is syslog system agnostic. just use the transform setting of splunk forwarder.
