### ISSUE TITLE
Filter out application related logs during the routing phase

### ISSUE THREAD

**Issue by claudio-benfatto** [cloudfoundry-community/firehose-to-syslog#122]
Hello here,

I'll try to describe our use case: we plan to use the `application syslog drain`  from the Doppler, to forward application logs directly to our logging system without passing via the nozzle. 
At the same time, we'd like to keep using the firehose-to-syslog nozzle to process the remaining component logs.

In order to avoid duplication, we'd like to discard all the logs defining a `cf_app_id` field during the routing phase in the `firehose-to-syslog`, probably adding a flag to the configuration options.

We do not mind contributing to the project and creating a pull request, but we wanted to ask you first if the feature is of any general interest or we'd better proceed to create our own fork.

Thank you!
Claudio

**Comment by shinji62** [comment]
not taking LogMessage do not work  ?

Thanks

**Comment by claudio-benfatto** [comment]
It should, I checked again.
 
I wasn't quite sure about the equality `Messages of type LogMessage` === `Application Messages forwarded by the syslog drain`.

But this seems to stand true.

Thanks for your help!
