### ISSUE TITLE
Allow use of the application-specific log stream endpoint

### ISSUE THREAD

**Issue by tomwhoiscontrary** [cloudfoundry-community/firehose-to-syslog#125]
This utility requires a quite broad permission to access the firehose. As a mere user, i don't have this permission. All i have is permission to access the log stream for a single application.

The [CF firehose plugin](https://github.com/cloudfoundry/firehose-plugin) is another tool for accessing the firehose, but it is a bit different. It [can use both API endpoints](https://github.com/cloudfoundry/firehose-plugin/blob/c0751c19fc9e262a46ca8dd12c96042774c951f2/firehose/client.go#L68
):

```go
	if len(c.options.AppGUID) != 0 {
		c.ui.Say("Starting the nozzle for app %s", c.options.AppGUID)
		output, errors = dopplerConnection.StreamWithoutReconnect(c.options.AppGUID, c.authToken)
	} else {
		subscriptionID := c.options.SubscriptionID
		if len(subscriptionID) == 0 {
			subscriptionID = "FirehosePlugin"
		}
		c.ui.Say("Starting the nozzle")
		output, errors = dopplerConnection.FirehoseWithoutReconnect(subscriptionID, c.authToken)
	}
```

It strikes me that it would be possible to do something a bit similar in firehose-to-syslog. By default, connect to the firehose, but if the user specifies a list of application GUIDs, then use the application-specific streams for each one instead. You would want to spawn a goroutine for each one, i suppose. This would allow unprivileged users like me to collect logs.

Would this be an appropriate change?

**Comment by shinji62** [comment]
No, That's not the purpose of this plugin.
You can use syslog drain if you want by app logs.
