### ISSUE TITLE
Format of the syslog message

### ISSUE THREAD

**Issue by kravell** [cloudfoundry-community/firehose-to-syslog#128]
Is there an easy way to format the messages being written to Syslog. I see that there is a standard text in the format of <6>2016-09-30T21:22:02Z lkjehidqrtt doppler[24]:  and then there is a the actual JSON message that has the details of the log message. We would like to just send the JSON as it would be easier to parse on the receiver side. 

Would really appreciate if you can tell me how to customize this. 

Thanks.

**Comment by shinji62** [comment]
That's firehose-to-"syslog" so it's send in syslog format.
Just fork the repository or create your own app.
Thanks
