### ISSUE TITLE
App Outputting wrong version

### ISSUE THREAD

**Issue by johnlonganecker** [cloudfoundry-community/firehose-to-syslog#130]
```
cf push
cf logs ...
....
Starting firehose-to-syslog 0.0.0
....
```

I suspect https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/main.go#L40 is the reason for this behavior

**Comment by shinji62** [comment]
No, the version is injecting during compiling phase.
You can check out here https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/Makefile

Basically just look for ```${BUILD_NUMBER}```.

**Comment by johnlonganecker** [comment]
I follow these instructions https://github.com/cloudfoundry-community/firehose-to-syslog#push-as-an-app-to-cloud-foundry and it is outputting what I sent before:

```
Starting firehose-to-syslog 0.0.0
```

What do I need to do differently?

**Comment by shinji62** [comment]
Well other choice is to download the compiled version (Releases) and use binary-buildpack. and trust what you are pushing to be the good version.

Go-buildpack do not support custom flag to build so no chance to passed the version.

**Comment by johnlonganecker** [comment]
When I was using an older version v1.3.1 I was able to see the proper version in cf logs. It was helpful to see that.

Thanks for taking the time to respond.
