### ISSUE TITLE
Do we really need cf_ignored_app=false in messages?

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/firehose-to-syslog#137]
Recently a new field `cf_ignored_app` was introduced (see https://github.com/cloudfoundry-community/firehose-to-syslog/issues/132).

I have a question. Can we omit `"cf_ignored_app": "false"` field for not-ignored applications when writing a message to syslog? This looks like a redundant info, but I'm not sure if is ok to omit it from implementation point of view.

**Comment by shinji62** [comment]
Agree that's not really convenient.
But this need a little bit of refactoring.

I will try to work on that when I have some time.

Thanks

**Comment by hannayurkevich** [comment]
Sure. Thank you!

**Comment by shinji62** [comment]
Done in 4.1.1
