### ISSUE TITLE
Logging events not being logged

### ISSUE THREAD

**Issue by bobbyhubbard** [cloudfoundry-community/firehose-to-syslog#138]
Maybe I misunderstand the "LOG_EVENT_TOTALS" options but my assumption is that it should at the interval specified by LOG_EVENT_TOTALS_TIME log stats about how many logs were processed. Correct? We dont see LOG_EVENT_TOTALS in the logs unless we have debug=true. Is it only available in debug mode? 

We are seeing major issues were randomly firehose-to-syslog will just stopping sending logs and we can't figure out why. We restart the firehose-to-syslog app and it starts feeding again. Its not helpful that the app doesnt output anything...no logs at all... once it gets running. 

Here is the manifest we're using. We are getting logs sent to syslog but no logs from the firehose-to-syslog instance itself.
```
memory: 128M
disk_quota: 64M
buildpack: go_buildpack_v1_7_12
no-route: true
health-check-type: none
instances: 2
env:
  API_ENDPOINT: https://api...
  DOPPLER_ENDPOINT: wss://doppler....
  FIREHOSE_USER: kafka-firehose-svc
  FIREHOSE_PASSWORD: ...
  LOG_EVENT_TOTALS: true
  LOG_EVENT_TOTALS_TIME: 10s
  SKIP_SSL_VALIDATION: true
  EXTRA_FIELDS: "datacenter:NONPROD"
  DEBUG: false
applications:
- name: logs-firehose-to-syslog-v2.4.1
  env:
    EVENTS: LogMessage
    FIREHOSE_SUBSCRIPTION_ID: logs-firehose-to-syslog
    SYSLOG_ENDPOINT: logstashsyslogfwd
```

**Comment by bobbyhubbard** [comment]
BTW - if I do enable DEBUG. Here is an example of the goofy output I am getting. What is with the msg field? Any ideas would be appreciated. 
[firehose-to-syslog-example.txt](https://github.com/cloudfoundry-community/firehose-to-syslog/files/704910/firehose-to-syslog-example.txt)

**Comment by shinji62** [comment]
> We are seeing major issues were randomly firehose-to-syslog will just stopping sending logs and we can't figure out why. 

If the nozzle could not connect to syslog or the loggregator endpoint you get errors ..
Well you should check if `cf logs` is working too as this time because if this is not working that's mean the issue is on the logs stack of CF / PCF

This logs event are since 2.0.0 sent to the syslog endpoint and not on stdin ...

Goofy output is something "normal" because you process your own logs again and again ...
`DEBUG` should be enable outside of CF like starting the app on your laptop.

**Comment by bobbyhubbard** [comment]
yeah `cf logs` is fine during an issue. We typically run two instances of the firehose-to-syslog and sometimes one instance will fail and the other will continue to send logs. Checking the app, cf logs works perfectly fine. doppler/firehose vm's are not CPU or IO bound at all. It seems as if its not refreshing the oauth token correctly. If I restart the firehose, it then works fine again for another few days. We did check syslog and so far we havent seen anything.

I hadnt thought about it logging itself into recursion hell...that makes sense now.  Is there a way to reinitialize the doppler token on error? Is it possible that the firehose-to-syslog could actually write its own logs to output and ignore subsequent reprocessing of those logs by some means? Syslog would work too. I just need some means of troubleshooting what the firehose-to-syslog app is actually experiencing.

**Comment by shinji62** [comment]
Could be related to refresh token. I will take a look on that.

**Comment by shinji62** [comment]
Ok I change the connection type, can you try this version 
`https://github.com/cloudfoundry-community/firehose-to-syslog/tree/feature/use_noaa_lib_for_firehose` ??

Just compile it. Oh you need to use client_id and client_secret connexion type.

**Comment by bobbyhubbard** [comment]
Hum, we are using the username/password connection. I'll need to create a client_Id secret and then retry this. I'll work on that now.

**Comment by bobbyhubbard** [comment]
Ok its running in our nonprod environment.  For the record, we never set the `FIREHOSE_CLIENT_ID` or `FIREHOSE_CLIENT_SECRET` options. Is this required in order to actually get the refresh token? Maybe that was our issue the whole time...

**Comment by bobbyhubbard** [comment]
@shinji62 I goofed when deploying and accidentally deployed master instead of the branch you specified. When I tried I get the following: 
```
-----> Using go1.7.4
 !!    Installing package '.' (default)
-----> Running: go install -v -tags cloudfoundry . 
uaatokenrefresher/uaa_token_refresher.go:7:2: cannot find package "github.com/cloudfoundry-incubator/uaago" in any of:
	/tmp/tmp.TXFXNcIzEe/.go/src/github.com/cloudfoundry-community/firehose-to-syslog/vendor/github.com/cloudfoundry-incubator/uaago (vendor tree)
	/tmp/cache/go1.7.4/go/src/github.com/cloudfoundry-incubator/uaago (from $GOROOT)
	/tmp/tmp.TXFXNcIzEe/.go/src/github.com/cloudfoundry-incubator/uaago (from $GOPATH)
uaatokenrefresher/uaa_token_refresher.go:8:2: cannot find package "github.com/shinji62/cf-cleanup-apps/logging" in any of:
	/tmp/tmp.TXFXNcIzEe/.go/src/github.com/cloudfoundry-community/firehose-to-syslog/vendor/github.com/shinji62/cf-cleanup-apps/logging (vendor tree)
	/tmp/cache/go1.7.4/go/src/github.com/shinji62/cf-cleanup-apps/logging (from $GOROOT)
	/tmp/tmp.TXFXNcIzEe/.go/src/github.com/shinji62/cf-cleanup-apps/logging (from $GOPATH)
Failed to compile droplet
Exit status 223
```

**Comment by shinji62** [comment]
Ok this time it's seems I missup something.
Let me take a look today.
Thanks.

**Comment by shinji62** [comment]
Should be ok now.
Sorry.

**Comment by bobbyhubbard** [comment]
Got it thanks. I tried to fix it but setting up Go proved more challenging than I thought. :) We're now running `feature/use_noaa_lib_for_firehose` in our non-prod CF foundation with client-based auth instead of user/password. So far so good.

**Comment by shinji62** [comment]
@bobbyhubbard Any updates ?

**Comment by bobbyhubbard** [comment]
I never got any logs before still doesnt seem to log much so its hard to validate without time... so far it looks good... :) Do you have a recommendation on how to validate this more time efficiently?

**Comment by shinji62** [comment]
To be honest, only long running test ...
Btw I am thinking about outputing the stats to stdin as well interested ?

**Comment by bobbyhubbard** [comment]
happy to test it but it invalidates the current test. :)

**Comment by shinji62** [comment]
@bobbyhubbard Check you pivotal slack. Thanks.

**Comment by shinji62** [comment]
2.5.0 get released and fix this issue.
