### ISSUE TITLE
exclude certain apps

### ISSUE THREAD

**Issue by warroyo** [cloudfoundry-community/firehose-to-syslog#139]
I see there is a feature for apps to set `cf_ignored-app` ,  however it would be nice to be able to specify an environment variable at the firehose-to-syslog app level to exclude certain applications. 

I have a use case where we run multiple firehose-to-syslog applications that send to different syslog endpoints. If an app specifies the `cf_ignore_app` environment variable it would be excluded from all instances of firehose-to-syslog. This is not ideal. I would like to be able to exclude different apps from each instance of the firehose-to-syslog app.

is there any way of doing this currently? If not can this feature be implemented ?

**Comment by shinji62** [comment]
Even if I understand I think this do not really make sens, as the uuid can change pretty often and the name is not uniq.


I don't want to make this nozzle more compilcated.
