### ISSUE TITLE
source_instance is always 0 for RTR LogMessages

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/firehose-to-syslog#14]
Given an app with 3 instances:
```
$ cf a
Getting apps in org system / space test as admin...
OK

name        requested state   instances   memory   disk   urls   
cf-env      started           3/3         128M     1G     cf-env.apps.54.183.203.97.xip.io   
```

Making 3 different requests to the app (and confirming via the browser output that each requests goes to a different cf-instance)

The RTR logs forwarded to syslog always have `"source_instance":"0",`

```
{"cf_app_id":"abfc9a95-d20c-44bb-9771-4aba27856843","level":"info","message_type":"OUT","msg":"cf-env.apps.54.183.203.97.xip.io - [04/04/2015:08:24:34 +0000] \"GET / HTTP/1.1\" 200 4283 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36\" 10.10.2.6:50837 x_forwarded_for:\"80.229.7.108, 10.10.2.6\" vcap_request_id:65583092-4d22-4de1-74e8-da86c9056be7 response_time:0.010811226 app_id:abfc9a95-d20c-44bb-9771-4aba27856843\n","source_instance":"0","source_type":"RTR","time":"2015-04-04T08:24:32Z"}
{"cf_app_id":"abfc9a95-d20c-44bb-9771-4aba27856843","level":"info","message_type":"ERR","msg":"80.229.7.108, 10.10.2.6 - - [04/Apr/2015 08:24:38] \"GET / HTTP/1.1\" 200 4344 0.0034","source_instance":"0","source_type":"App","time":"2015-04-04T08:24:35Z"}
{"cf_app_id":"abfc9a95-d20c-44bb-9771-4aba27856843","level":"info","message_type":"OUT","msg":"cf-env.apps.54.183.203.97.xip.io - [04/04/2015:08:24:37 +0000] \"GET / HTTP/1.1\" 200 4344 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36\" 10.10.2.6:50837 x_forwarded_for:\"80.229.7.108, 10.10.2.6\" vcap_request_id:b6b1938d-0677-4b41-76ec-79818acdfb61 response_time:0.018241253 app_id:abfc9a95-d20c-44bb-9771-4aba27856843\n","source_instance":"0","source_type":"RTR","time":"2015-04-04T08:24:35Z"}
{"cf_app_id":"abfc9a95-d20c-44bb-9771-4aba27856843","level":"info","message_type":"ERR","msg":"80.229.7.108, 10.10.2.6 - - [04/Apr/2015 08:24:40] \"GET / HTTP/1.1\" 200 4344 0.0106","source_instance":"1","source_type":"App","time":"2015-04-04T08:24:37Z"}
{"cf_app_id":"abfc9a95-d20c-44bb-9771-4aba27856843","level":"info","message_type":"OUT","msg":"cf-env.apps.54.183.203.97.xip.io - [04/04/2015:08:24:39 +0000] \"GET / HTTP/1.1\" 200 4344 \"-\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36\" 10.10.2.6:50837 x_forwarded_for:\"80.229.7.108, 10.10.2.6\" vcap_request_id:d8623d66-2b91-4e64-4662-0b09c2621d49 response_time:0.017076269 app_id:abfc9a95-d20c-44bb-9771-4aba27856843\n","source_instance":"0","source_type":"RTR","time":"2015-04-04T08:24:37Z"}
```

It seems that the source_instance changes for other message_types - eg `"source_type":"App"`
 
Shouldn't we be seeing multiple source_instances for the RTR logs too?

**Comment by mrdavidlaing** [comment]
@simonjohansson - Is this a bug, or a quirk of `"source_type":"RTR"` LogMessages?

**Comment by simonjohansson** [comment]
@mrdavidlaing Im just on my way out, so I wont have time to look into this right now. But if I remember correctly the source_instance in the context of a RTR even is the index of the Gorouter, even so this index should be chaning. How many requests did you do?

I will double check later, and if thats the case the field name should be rewritten to something more descriptive, router_instance, maybe?

**Comment by mrdavidlaing** [comment]
Aha - that makes more sense.  I think we only have 1 router, which would
explain why it's always 0 for RTR and changed for type App.

If that is the case, I don't think we should change the name, but rather
document that source_instance is the go router instance in the case of RTR
log messages.

On Saturday, April 4, 2015, Simon Johansson <notifications@github.com>
wrote:

> @mrdavidlaing <https://github.com/mrdavidlaing> Im just on my way out, so
> I wont have time to look into this right now. But if I remember correctly
> the source_instance in the context of a RTR even is the index of the
> Gorouter, even so this index should be chaning. How many requests did you
> do?
>
> I will double check later, and if thats the case the field name should be
> rewritten to something more descriptive, router_instance, maybe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-community/firehose-to-syslog/issues/14#issuecomment-89538777>
> .
>


-- 
David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by simonjohansson** [comment]
@mrdavidlaing I just double checked this against our production environment where we have more than one Gorouter, and source_instance is indeed always set to 0.

**Comment by mrdavidlaing** [comment]
Hmm.  So there is a bug somewhere ?

On Saturday, April 4, 2015, Simon Johansson <notifications@github.com>
wrote:

> @mrdavidlaing <https://github.com/mrdavidlaing> I just double checked
> this against our production environment where we have more than one
> Gorouter, and source_instance is indeed always set to 0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudfoundry-community/firehose-to-syslog/issues/14#issuecomment-89672591>
> .
>


-- 
David Laing
logsearch.io - build your own open source cloud logging cluster
http://davidlaing.com

**Comment by simonjohansson** [comment]
I dont know if its necessarily a bug.
Might be that the source instance doesn't make sense for RTR. 

Need to have a deeper look at the loggregator src to see where the event gets fired off from.

**Comment by amhuber** [comment]
FYI, with the latest develop code this appears to be working correctly:

    "origin":"router__0","source_instance":"0","source_type":"RTR"
    "origin":"router__2","source_instance":"2","source_type":"RTR"
    "origin":"router__1","source_instance":"1","source_type":"RTR"

**Comment by shinji62** [comment]
yes fix.
