### ISSUE TITLE
Support end to end TLS encryption to the Syslog endpoint

### ISSUE THREAD

**Issue by kelapure** [cloudfoundry-community/firehose-to-syslog#142]
# Do we have any plans to add encryption TLS support to the Firehose2Syslog nozzle ?

We love the Firehose2Syslog nozzle and have deployed it at numerous customer deployments. At a major customer we have a requirement of encrypting the stream emanating from the Firehose2Syslog nozzle … 

They have to outbound encrypt the stream when it leaves the nozzle to the Syslog endpoint. Do we have any plans for adding TLS encryption to the Firehose2Syslog nozzle.... The customer has written a custom tile to do this which we would like to retire ....

Please let us know if you need any more information 

-cheers,
Rohit

**Comment by shinji62** [comment]
Yes,
I will work on that soon.

I need to finish some ongoing work then I will start on that.

**Comment by shinji62** [comment]
I starting working on that on the branch https://github.com/cloudfoundry-community/firehose-to-syslog/tree/feature/tls-new-syslog-hook

It's still early beta but if you want to try, you need to add `--syslog-protocol="tcp+tls"` (TLS-encrypted TCP) then you need provide a path with the encoded PEM cert `--cert-pem-syslog="yourpath/pemfile"`


You can use this script to generate TLS if you want `https://github.com/RackSec/srslog/blob/master/script/gen-certs.py`

**Comment by kelapure** [comment]
Definitely taking this out for a spin today.

Sent from my iPhone,
Rohit

**Comment by shinji62** [comment]
Let me know how is going.

thanks

**Comment by shinji62** [comment]
This have been merge to the 3.0 version.
