### ISSUE TITLE
division by zero error

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-community/firehose-to-syslog#145]
We are seeing a *division by zero* with the nozzle. We are unsure of the cause, but have validated the firehose is behaving as expected.

Because of communication channels, a screenshot is all I can provide of the stack trace:

<img width="1156" alt="firehose-to-syslog25" src="https://cloud.githubusercontent.com/assets/75184/26362749/35ea0f3e-3f9c-11e7-9719-f230b1c4c0dc.png">

**Comment by shinji62** [comment]
Can I have the version use by the customer ?

According to what I see, it seems they use CF / Go buildpack to push the app, so difficult to get the version.

Please ask them.
thanks.

**Comment by jtarchie** [comment]
app: v2.5
go version: 1.7.1

**Comment by shinji62** [comment]
Thanks.

**Comment by shinji62** [comment]
Does this still hapening ?

**Comment by shinji62** [comment]
Fixed in https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/3.3.0
