### ISSUE TITLE
incoming chunk is broken

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry-community/firehose-to-syslog#147]
Error pushing log to Fluentd server

```
2017-06-06 20:21:13.190692477 +0000 fluent.warn: {"host":"172.17.0.1","msg":52,"message":"incoming chunk is broken: host=\"172.17.0.1\" msg=52"}
2017-06-06 20:21:13.190722824 +0000 fluent.warn: {"host":"172.17.0.1","msg":125,"message":"incoming chunk is broken: host=\"172.17.0.1\" msg=125"}
2017-06-06 20:21:13.190747660 +0000 fluent.warn: {"host":"172.17.0.1","msg":10,"message":"incoming chunk is broken: host=\"172.17.0.1\" msg=10"}

```

Could you tell me what causes the problem. When i use different source it works.
Thanks

**Comment by shinji62** [comment]
What are you using ? syslog input in fluentd ? Logs are formatted in syslog format [RFC5424](https://datatracker.ietf.org/doc/rfc5424/).

**Comment by fghorbel** [comment]
Yes, You are right!
At the beginning, i had got it to work with tcp input in fluentd. afterwards, i tried the syslog input and it worked as expected. 

```
<source>
  @type syslog
  port 20002
  tag system
</source>

```

Thank you.

**Comment by shinji62** [comment]
Welcome.

**Comment by fghorbel** [comment]
Hi  shinji62, 

When i run 
`firehose-to-syslog --api-endpoint="https://api.sy....  --syslog-protocol=tcp`

i see this error from fluentd logs

```
"failed to parse message data=\"<6> 2017-06-16T21:23:38Z sdp-vpc.localdomain-docker-sdp-us-east-1 doppler[3838]: {\\\"cf_app_id\\\":\\\"67996643-2578-4279-bcff-c4802ce7f982\\\",\\\"cf_app_name\\\":\\\"machine-service\\\",\\\"cf_ignored_app\\\":false,\\\"cf_org_id\\\":\\\"5402191d-1cf4-4cec-b348-534ed5ebad92\\\",\\\"cf_org_name\\\":\\\"devops\\\",\\\"cf_origin\\\":\\\"firehose\\\",\\\"cf_space_id\\\":\\\"e9fd46b5-7c40-4d92-b51c-1f3786d4160f\\\",\\\"cf_space_name\\\":\\\"testing\\\",\\\"deployment\\\":\\\"us-east-1-10.13\\\",\\\"event_type\\\":\\\"LogMessage\\\",\\\"ip\\\":\\\"10.153.871.6\\\",\\\"job\\\":\\\"diego_cell_z2\\\",\\\"job_index\\\":\\\"2add2fvhg2e0-f3b0-4750-a916-0f10a8dfc64e\\\",\\\"level\\\":\\\"info\\\",\\\"message_type\\\":\\\"OUT\\\",\\\"msg\\\":\\\"DEBUG  c.p.m.AuthenticationFilter unsupported authentication type null\\\",\\\"origin\\\":\\\"rep\\\",\\\"source_instance\\\":\\\"0\\\",\\\"source_type\\\":\\\"APP/PROC/WEB\\\",\\\"time\\\":\\\"2017-06-16T21:23:38Z\\\",\\\"timestamp\\\":1497648218409276091}\""}

```

I assume, the because the `message` key doesn t exist. 

I  tried to use the plugin 

```

<source>
  @type syslog
  port 20322
  tag firehose-to-reform
  format json
</source>

<filter firehose-to-reform>
    type record_transformer
    enable_ruby
    <record>
      message ${record["msg"]}
    </record>
</filter>

```

but it didn t work.

Could you tell me why the transformation didnt work?

I also tried the tcp type, however, i was able to get the regex works. 

Thank you.

**Comment by makknife** [comment]
You need `format none` in <source></source>

# The none parser plugin parses the line as-is with single field. This format is to defer parsing/structuring the data.
#   If the format parameter is missing, then the log data is assumed to have the canonical syslog 
Logs will have a message key though

https://docs.fluentd.org/v0.12/articles/parser_none
https://docs.fluentd.org/v0.10/articles/in_syslog
