### ISSUE TITLE
Throttle CC calls if app is no longer in CC DB

### ISSUE THREAD

**Issue by muymoo** [cloudfoundry-community/firehose-to-syslog#149]
_From @muymoo on June 19, 2017 17:20_

We have about 120,000 events/s coming off the firehose. When we enable `ADD_APP_INFO`, we get into a state where there are logs coming off the firehose with app id's that no longer exist in the CC DB (this might be a separate problem on its own). This causes the nozzle to repeatedly call the CC API with the app guid that no longer exists. This significantly slows down the nozzle (by 90%). I've been trying some hacks with a syncmap that stores app id's which no longer exist and ignores those calls. The other option I've been thinking about is creating an empty app record in Boltdb. Ideas?

_Copied from original issue: cloudfoundry-community/splunk-firehose-nozzle#39_

**Comment by muymoo** [comment]
A hack that I made "works" is to use a `syncmap` in the boltdb caching implementation:

```golang
import "golang.org/x/sync/syncmap"
...
	return &CachingBolt{
		GcfClient: gcfClientSet,
		Appdb:     db,
		missed:	   new(syncmap.Map), // Stores app guids that no longer exist in CC DB but are still coming off firehose
	}
...
	var ticker = time.Tick(1 * time.Hour)

	go func() {
		for range ticker {
			c.missed = new(syncmap.Map) // Clear the map once an hour
		}
	}()
...
func (c *CachingBolt) GetAppInfoCache(appGuid string) App {
	
	// App exists in cache
	if app := c.GetAppInfo(appGuid); app.Name != "" {
		return app
	}
	
	// App already missed, ignore
	if _, found := c.missed.Load(appGuid); found {
		return App{}
	}

	// First time seeing event from app
	apps:=c.GetAppByGuid(appGuid)
	if apps[0].Name == ""{
		
		// Remember not to look up this app again
		c.missed.Store(appGuid,0)
		return App{}
	}
	return apps[0]
}
```

**Comment by muymoo** [comment]
https://github.com/muymoo/splunk-firehose-nozzle/tree/feature/ignore-missing-apps

**Comment by muymoo** [comment]
_From @chenziliang on June 20, 2017 18:38_

@muymoo Thanks for these changes. Could you please create a PR for this ?

**Comment by muymoo** [comment]
@chenziliang Would you like this to the firehose-to-syslog (https://github.com/cloudfoundry-community/firehose-to-syslog) repo instead of the vendor folder here?

**Comment by muymoo** [comment]
_From @chenziliang on June 20, 2017 18:48_

Seems the root cause is in syslog which splunk nozzle leverage, i would suggest fixing problem there.

**Comment by muymoo** [comment]
Here's the code. Shall I make a PR? https://github.com/muymoo/splunk-firehose-nozzle/commit/b4c672e76761b0cc705d3af76796b2e2bb447836

**Comment by chenziliang** [comment]
This is something i was looking for. @muymoo  Could you please fork the latest develop branch since, there are some changes to latest dev branch. And before submit code review, you can run "make build" and "make testall" to format the code and test the code etc

**Comment by shinji62** [comment]
Hi,

I will take a look.   But for me the biggest issue is `app guids that no longer exist in CC DB but are still coming off firehose`

What you propose is just a band-aid ... Problem should be Why the firehose still send invalid uuid ... That's could be the issue ..

I would rather prefer to work on another implementation with BoltDB instead of using in memory Map.

I guess I got the issue, but do you know how to replicate it ?

**Comment by shinji62** [comment]
Another issue is what do you want to do with invalid uuid app ? just trow it away ?
This could be easier.
And I think cleaning bucket of empty app every 2 hours could be good too, that will avoid the Boltdb to grow too much because of garbage.

**Comment by shinji62** [comment]
@jasonkeene and @ahevenor Do you know something about this bad uuid behavior ?

**Comment by shinji62** [comment]
@muymoo I am curious about your number of nozzle / doppler / trafficconttroller for this 120K / sec event.

Btw which CF version are you using ?

Thanks

**Comment by muymoo** [comment]
@shinji62 Agreed on fixing the root cause too. But the nozzle should still be resilient. It went into self destruct mode when logs from a missing app came in and kept calling the CC API over and over again.

We have two cases where an app may not exist:
1. The above mentioned state where logs are coming from app that no longer exists in the CC DB. My guess is this happens when the dopplers get backed up. Not concrete numbers on this, but the log messages that come through are usually from minutes-hours in the past in these cases.
2. Our CC DB is so big that we have a duplicate of it that we use to query against (so we don't hurt our primary CC). It's replicated every 2 hours so we may not have the app in the duplicated DB.

**Comment by muymoo** [comment]
@shinji62 If I switch this over to use Boltdb, would you be interested in PR?

**Comment by shinji62** [comment]
Yes for the PR with Boltdb and do not forget a periodic cleaning mechanism in case where the app get added to your replicated DB.

Anyway I am still interesting by the number of doppler/TC/ nozzle that your are using for your log.

Thanks

**Comment by muymoo** [comment]
20 doppler/20 TC/50 nozzles

**Comment by shinji62** [comment]
Humm, nozzle should be able to handle around 10K message and the doppler / TC should be kind of bottleneck .. Are you is not 50 Doppler / 20 TC / 10 nozzles ?


Thanks

**Comment by chenziliang** [comment]
@shinji62 May i ask why we introduce boltDB into firehose-to-syslog ? What are the major consideration ? Can we just use in-memory cache  ?

**Comment by shinji62** [comment]
@chenziliang Well botld use Memory (a part of) too, and easy to use, and when the application restart and so on, you data will still be there.
No plan to change that.

**Comment by chenziliang** [comment]
@shinji62 If the application is running in a container (or like stuff), and the container come and go (application crashes / restarts), it doesn't persistent the boltd local db across the restart ?

**Comment by shinji62** [comment]
@chenziliang Agree but firehose-to-syslog can run on VM too, with persistent disk, or even local disk with persist across application restart (not VM restart) ... 

If you think boltdb is not a good fit for you, just write your own caching based on the caching interface.

**Comment by chenziliang** [comment]
@shinji62 Thanks for this information. Just like to understand the benefits the local boltdb introduces.
