### ISSUE TITLE
noaa dependency is out of date

### ISSUE THREAD

**Issue by sharms** [cloudfoundry-community/firehose-to-syslog#158]
Currently when firehose-to-syslog experiences a network disruption, it will not resume the connection or provide logs indicating that the connection is not working.  After reviewing the code, we believe some of the timeout and connection error handling features in noaa would address some of this, however the current copy bundled is from early 2016.

Is it possible to bundle a current version?

**Comment by shinji62** [comment]
I will check.
Thanks

**Comment by shinji62** [comment]
Updated  in https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/3.3.0
