### ISSUE TITLE
un-expected Event Type in syslog message

### ISSUE THREAD

**Issue by cmarchw** [cloudfoundry-community/firehose-to-syslog#163]
We are seeing an un-expected even type in our logs and I was hoping you could explain why that is. We have the set events = LogMessae, Error.  The question is, why are we seeing messages with an even_type of "firehose_to_syslog_stats" being sent to syslog?

Example. 
{"LogMessage":345415509,"by_sec_Events":4483,"cf_origin":"firehose",**"event_type":"firehose_to_syslog_stats**","level":"info","msg":"Statistic for firehose to syslog","time":"2017-11-06T13:40:43Z","total_count":345415509}

**Comment by shinji62** [comment]
Hi,

That an even of f2s itself, you can disable it by omitting the params `--log-event-totals `
https://github.com/cloudfoundry-community/firehose-to-syslog/blob/3.3.2/eventRouting/eventrouting_default.go#L122

It's remove on the 4.0.0 version.

Thanks
