### ISSUE TITLE
certificate addition

### ISSUE THREAD

**Issue by renuy** [cloudfoundry-community/firehose-to-syslog#165]
Have installed f2s as an application in PCF and forwarding to a syslog server. However would want all the logs being given to the server, encrypted.
How to specify the certificate (contents to be given or file path)?
How can i specify it in the manifest.yml?

**Comment by shinji62** [comment]
Just push a cert pem encoded file.

https://github.com/cloudfoundry-community/firehose-to-syslog#tls-syslog-endpoint
