### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by ap1256** [cloudfoundry-community/firehose-to-syslog#178]
We are seeing some unicode characters coming out of the app. Is there a way to not encode them?
For example:
The sample Log from PCF command line:
DEBUG TaskEntity.selectTaskByQueryCriteria - <== Total: 0

But output from this app is 
DEBUG TaskEntity.selectTaskByQueryCriteria - \u003c== Total: 0

In addition to avoid having stacktrace as muliple log messages, we can converting the newline to unicode. But it is escaping the "\"
The sample Log from PCF command line:
TEST-DEBUG controller.HelloWorldController - testing mulitple lines\u2028line1\u2028Line2\u2028
But output from this app is 
TEST-DEBUG controller.HelloWorldController - testing mulitple lines\\u2028line1\\u2028Line2\\u2028

**Comment by shinji62** [comment]
We Json encode by default. 

Try to use textformatter instead of default Json
