### ISSUE TITLE
Websocket Close 1006 abnormal closure

### ISSUE THREAD

**Issue by bradgoodman** [cloudfoundry-community/firehose-to-syslog#180]
We are currently using the 4.0.3 release using the binary buildpack. When running the firehose nozzle we are receiving these errors. 

`Message: Error while reading from the Firehose:  Details: websocket: close 1006 (abnormal closure): unexpected EOF`

`2018-03-13T11:32:42.76-0500 [APP/PROC/WEB/0] ERR 2018/03/13 16:32:42 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>`

App Env:

> API_ENDPOINT: https://api.sys.foundation.domain.com
> DEBUG: false
> DOPPLER_ENDPOINT: wss://doppler.sys.foundation.domain.com443
> EVENTS: LogMessage, Error
> EVENTS_FIELDS: foundation
> FIREHOSE_CLIENT_ID: This was a client ID
> FIREHOSE_CLIENT_SECRET: This was a password
> FIREHOSE_SUBSCRIPTION_ID: elk
> LOG_EVENT_TOTALS: true
> LOG_EVENT_TOTALS_TIME: 10s
> LOG_FORMATTER_TYPE: json
> SKIP_SSL_VALIDATION: true
> SYSLOG_ENDPOINT: This was a logstash endpoint
>

**Comment by shinji62** [comment]
Seems websocket or connexion was closed ? It this happen during update or so on ?

**Comment by shinji62** [comment]
@bradgoodman

**Comment by shinji62** [comment]
No update..
