### ISSUE TITLE
Has the filter option been removed

### ISSUE THREAD

**Issue by filidav** [cloudfoundry-community/firehose-to-syslog#188]
filters="org_name:org1,org2|space_id:asff-12ffa,1122-dbfa-aaaa|app_name:app1"

I see the commit here
https://github.com/cloudfoundry-community/firehose-to-syslog/pull/65/commits/8f201a2f5823fad71039c0e76b4149e415035375

I don't see it in the here
https://github.com/cloudfoundry-community/firehose-to-syslog#options

**Comment by shinji62** [comment]
Filter have never been merged or existing in firehose-to-syslog as I remind it's just a close PR. 

https://github.com/cloudfoundry-community/firehose-to-syslog/pull/65
