### ISSUE TITLE
F2S_DISABLE_LOGGING = true -- v5.0.0 -- does not disable logging 

### ISSUE THREAD

**Issue by Scoobed** [cloudfoundry-community/firehose-to-syslog#208]
F2S_DISABLE_LOGGING = true -- does not disable logging.  

Does not set IgnoredApp to true in the boltdb.

Thus we this flag to stop flooding, but as it did not work.  Only option was to stop the App, to stop the flooding.

**Comment by shinji62** [comment]
Should work, the issue maybe could be the time of the apps info are reloaded in boltDB or memory.

**Comment by geofffranks** [comment]
The env var was set over weekend, and it was still not recognizing it Monday. Did something change in the 5.0.0 release to how the environment data is gathered from CF?

**Comment by Scoobed** [comment]
Ok when digging through the caching code...   

It looks to never goes back to the cache to the look it up again  (After)
	var rv entity
	err = c.store.Get(makeCacheStorageKey(entityType, uuid), &rv)
	switch err {
	case nil:
		if rv.TTL.After(time.Now()) {
			return &rv, nil
                         //continue
		}
		// else continue
	case ErrKeyNotFound:
		// continue
	default:
		return nil, err
	}

If we were to change the rv.TTL.Before -- it would look it when the TTL expired...

	var rv entity
	err = c.store.Get(makeCacheStorageKey(entityType, uuid), &rv)
	switch err {
	case nil:
		if rv.TTL.Before(time.Now()) {
			return &rv, nil
                         //continue
		}
		// else continue
	case ErrKeyNotFound:
		// continue
	default:
		return nil, err
	}

**Comment by shinji62** [comment]
It should go back, but randomly as cache will be invalidated https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/caching/caching_lazyfill.go#L153

**Comment by Scoobed** [comment]
Is there a way to test that, because that is not what we are seeing?

**Comment by jmprice** [comment]
The documentation says to create a UAA client with:
 --authorities doppler.firehose,cloud_controller.global_auditor

But apparently "cloud_controller.global_auditor" doesn't have sufficient authority to read the application environment vars so the IgnoredApp property in the BoltDB is never changed to true.

Changing your UAA Client to have "cloud_controller.admin_read_only" allows the app to be ignored again.

**Comment by Scoobed** [comment]
We will give it a try and see it fixes the issue

**Comment by Scoobed** [comment]
The above fixes the problem -- we recreated the UUA client with the correct permission and I used that setting today to stop an apps logging. -- I did have to cause a `cf restage [app_name]` to pick up the environmental setting
