### ISSUE TITLE
Panic:  github.com/boltdb/bolt.(*Bucket).Get

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry-community/firehose-to-syslog#21]
Getting another error testing the latest code, this appears to be related to the Bolt DB?  The nozzle is crashing instantly with the first log entry, not sure how to debug this.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x8 pc=0x4587c3]

    goroutine 1 [running]:
    github.com/boltdb/bolt.(*Bucket).Get(0x0, 0xc208237b00, 0x24, 0x30, 0x0, 0x0, 0x0)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:256 +0x53
    github.com/cloudfoundry-community/firehose-to-syslog/caching.func·002(0xc2082e80d0, 0x0, 0x0)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching.go:71 +0xbf
    github.com/boltdb/bolt.(*DB).View(0xc2080389c0, 0xc20807e968, 0x0, 0x0)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:536 +0xe7
    github.com/cloudfoundry-community/firehose-to-syslog/caching.GetAppInfo(0xc208237ad0, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching.go:73 +0x9f
    github.com/cloudfoundry-community/firehose-to-syslog/logging.getAppInfo(0xc208237ad0, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/logging/logging.go:31 +0x52
    github.com/cloudfoundry-community/firehose-to-syslog/logging.LogMessages(0xc20810afa0)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/logging/logging.go:131 +0x19b
    github.com/cloudfoundry-community/firehose-to-syslog/events.RouteEvents(0xc2080332c0, 0xc20803d500)
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/events/events.go:25 +0x15c
    main.main()
            /var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/main.go:80 +0x7df

**Comment by shinji62** [comment]
Does your user can write to the folder where the my.db is ?
try to put my.db into the tmp directory

**Comment by amhuber** [comment]
I've got this inside a BOSH release so it was creating the file in the monit directory but the file was there.  I've changed it to /tmp for testing and it's creating the file there as well, exact same error.  Anything else I can check?

**Comment by shinji62** [comment]
Where is the bosh release  ? I could not reproduce the issue :/

**Comment by amhuber** [comment]
I've got a job and package included in an internal BOSH release that we use, but I just copied those from https://github.com/logsearch/logsearch-for-cloudfoundry/tree/master/logsearch-for-cloudfoundry-boshrelease.  I'll try to build the nozzle outside the release and test it in our environment to see if I get the same thing.

**Comment by shinji62** [comment]
Ok let me know

**Comment by amhuber** [comment]
I can't even do a go get, am I doing something wrong here?

go get github.com/cloudfoundry-community/firehose-to-syslog
package github.com/cloudfoundry-community/firehose-to-syslog
        imports github.com/Sirupsen/logrus
        imports github.com/Sirupsen/logrus/hooks/syslog
        imports github.com/SpringerPE/firehose-to-syslog/token
        imports github.com/SpringerPE/firehose-to-syslog/token
        imports github.com/SpringerPE/firehose-to-syslog/token: cannot find package "github.com/SpringerPE/firehose-to-syslog/token" in any of:
        /root/.gvm/gos/go1.4.2/src/github.com/SpringerPE/firehose-to-syslog/token (from $GOROOT)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/SpringerPE/firehose-to-syslog/token (from $GOPATH)

**Comment by shinji62** [comment]
use godep
```
godep go build
```

**Comment by amhuber** [comment]
Ah, it's pulling from the master branch, that makes sense.  So the build worked just fine once I checked out develop and used "godep" but I got exactly the same error.  :-(  This is on CF v207, by the way.

**Comment by amhuber** [comment]
Just FYI:

    root@fm7-nozzle01:~/.gvm/pkgsets/go1.4.2/global/src/github.com/cloudfoundry-community/firehose-to-syslog# ./firehose-to-syslog --version
    0.0.2 - ba541ca
    root@fm7-nozzle01:~/.gvm/pkgsets/go1.4.2/global/src/github.com/cloudfoundry-community/firehose-to-syslog# sha1sum firehose-to-syslog
    fd0a580657c9d27e39d3aec22b9d11e948e84168  firehose-to-syslog

**Comment by amhuber** [comment]
Also, if it helps, here is the data from the earlier version of the nozzle before I upgraded it this morning.  This is the same app I'm hitting to test the new code:

    Apr 20 21:14:21 911fa824-9a4c-4023-8708-3f70b63b7b07 doppler[25854]: {"cf_app_id":"5a5540ff-20bf-47fd-a756-85f80a8dfe63","event_type":"LogMessage","level":"info","message_type":"ERR","msg":"10.24.120.62, 10.65.25.205 - - [20/Apr/2015:21:14:21 +0000] \"GET / HTTP/1.1\" 200 274 0.2650","origin":"dea_logging_agent","source_instance":"1","source_type":"App","time":"2015-04-20T21:14:21Z","timestamp":1429564461691197897}
    Apr 20 21:14:21 911fa824-9a4c-4023-8708-3f70b63b7b07 doppler[25854]: {"cf_app_id":"5a5540ff-20bf-47fd-a756-85f80a8dfe63","event_type":"LogMessage","level":"info","message_type":"OUT","msg":"swift-monitor.paaslab3.xxx.xxx.com - [20/04/2015:21:14:21 +0000] \"GET / HTTP/1.1\" 200 274 \"-\" \"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)\" 10.65.25.205:55167 x_forwarded_for:\"10.24.120.62, 10.65.25.205\" vcap_request_id:ee34472d-3476-4cb3-5ac3-375e680f5ca2 response_time:0.296414646 app_id:5a5540ff-20bf-47fd-a756-85f80a8dfe63\n","origin":"router__2","source_instance":"2","source_type":"RTR","time":"2015-04-20T21:14:21Z","timestamp":1429564461692340849}

**Comment by shinji62** [comment]
Ok will try with 207

**Comment by amhuber** [comment]
I just tried it against an environment running v203 and it worked fine, no errors and I've got log data being sent.  On the v203 environment I can see app entries in my.db whereas in v207 the file just looks empty.  A change in the API perhaps?

**Comment by shinji62** [comment]
yes need to check ..

**Comment by mrdavidlaing** [comment]
FWIW, I'm testing using CF v206, and its working; so I suspect this is related to a change between v206 & v207.

**Comment by shinji62** [comment]
Just run against 207 and it works 
```
{"cf_app_id":"a29b4e9f-6cde-434b-8133-b77c3f3f7af7","cf_app_name":"myphp","cf_org_id":"8e36e45e-42e3-40ac-9b0d-03d20a419b2b","cf_org_name":"GWENN","cf_space_id":"2e87a35a-97a4-4883-965e-2a3f868e209d","cf_space_name":"GWENN-SPACE","event_type":"LogMessage","level":"info","message_type":"OUT","msg":"01:13:26 httpd   | 192.168.50.1 - - [22/Apr/2015:01:13:26 +0000] \"GET / HTTP/1.1\" 200 65029 vcap_request_id=c66d12c6-c848-463e-4536-c75824bae402 peer_addr=10.0.2.15","origin":"dea_logging_agent","source_instance":"0","source_type":"App","time":"2015-04-21T18:28:18-07:00","timestamp":1429665206520433465}
{"cf_app_id":"a29b4e9f-6cde-434b-8133-b77c3f3f7af7","cf_app_name":"myphp","cf_org_id":"8e36e45e-42e3-40ac-9b0d-03d20a419b2b","cf_org_name":"GWENN","cf_space_id":"2e87a35a-97a4-4883-965e-2a3f868e209d","cf_space_name":"GWENN-SPACE","event_type":"LogMessage","level":"info","message_type":"OUT","msg":"01:13:26 httpd   | 192.168.50.1 - - [22/Apr/2015:01:13:26 +0000] \"GET /index.php?=PHPE9568F34-D428-11d2-A769-00AA001ACF42 HTTP/1.1\" 200 2524 vcap_request_id=a60b0b3d-3017-40ab-56a1-6a784660887b peer_addr=10.0.2.15","origin":"dea_logging_agent","source_instance":"0","source_type":"App","time":"2015-04-21T18:28:18-07:00","timestamp":1429665206531632620}
```

**Comment by shinji62** [comment]
Maybe you can get the message you cause this error put some fmt.Print on the code.

**Comment by amhuber** [comment]
OK, I added in some debug code and in hindsight this is very obvious.  If the user is configured per the README with only the doppler.firehose role then it doesn't have permission to query all apps to fill the cache.  :-)  I was testing in my v207 environment with a user with only that role and in my v203 environments with the admin user, hence the different behavior.  The fix is to give the user more permissions.  I'll test out what the minimum required roles are to be able to query the info and reply so you can update the README.

The other issue is that you should probably throw an error and exit if you get nothing back from ListApps() as clearly the later code will crash if it tries to lookup an app and it's not in the database.

Aaron

**Comment by amhuber** [comment]
Just to confirm, the new PR did fix the crash when the user does not have the role to pull a list of all apps.  Now when using a user that has only doppler.firehose the logs work correctly but all of the new fields are just empty.  Still testing to see what role is required to pull the app list (hopefully just cloud_controller.read).

**Comment by shinji62** [comment]
yes because user should be able to query the cc, it s the only way to know apps information.

**Comment by amhuber** [comment]
It appears that cloud_controller.admin is required for this to work, which makes sense as it has to query app info across all orgs and spaces.  Here is the scim configuration I just tested:

    - user|password|cloud_controller.admin,doppler.firehose

You might want to document both options for completeness if people don't need the extra info and don't want the user to be an admin (doppler.firehose only for simple logs, admin and firehose for logs+metadata).

Thanks for the quick fix but in my case I'll just give the user admin rights.

Aaron
