### ISSUE TITLE
Add documentation for --events options

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/firehose-to-syslog#24]
The `--events` flag allows subscription to the following `event` types:

* HttpStart
* HttpStop
* Heartbeat
* HttpStartStop
* LogMessage
* ValueMetric
* CounterEvent
* Error
* ContainerMetric

We should add / link to documentation describing what these different event types are, and what fields are contained therein.

**Comment by mrdavidlaing** [comment]
@shinji62, @simonjohansson - any idea where documentation on the event types exists?

**Comment by shinji62** [comment]
No idea .. maybe here https://github.com/cloudfoundry/noaa/tree/master/events

**Comment by mrdavidlaing** [comment]
@shinji62 - thanks for the pointer, from there I found this: - https://github.com/cloudfoundry/dropsonde-protocol/blob/master/events/README.md
