### ISSUE TITLE
Remove grok-pattern in favour of pointing at logsearch-for-cloudfoundry

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/firehose-to-syslog#25]
I'd like to propose that we remove the embedded `grok-pattern/` folder, and rather point people at the https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/target/logstash-filters-default.conf if they are interested in logstash filters.

firehose-to-syslog is about forwarding CF firehost to a generic syslog endpoint.  The fact that logstash can be used as said syslog endpoint shouldn't be a concern of this codebase.

**Comment by mrdavidlaing** [comment]
@simonjohansson - thoughts?

**Comment by simonjohansson** [comment]
@mrdavidlaing sorry, just got back to work after a holiday.

I agree. Feel free to update the README!

**Comment by simonjohansson** [comment]
Removed the folder and updated README.

**Comment by mrdavidlaing** [comment]
@simonjohansson - Thanks for doing this for me.  I kept meaning to get to it; but never did
