### ISSUE TITLE
Create a new release.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/firehose-to-syslog#26]
Hiya all!

Amazing, coming back from holiday and see so much work have been done! 

With so much work going on, should we start thinking about a way to structure new releases, CHANGELOG, features and stuff like this, there is a lot of changes from 0.0.2 to HEAD on develop, almost to many.. :) 

Also, how do you feel about git flow? The tests are not really there yet, but should we use travis or similar tool to run the few ones we have?

**Comment by simonjohansson** [comment]
I took the liberty to add milestone 0.0.3 to the open issues. Lets create a new release once they are resolved.

**Comment by shinji62** [comment]
Gitfow is ok for me. 
Anyway will be time to merge to master

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/0.1.0
