### ISSUE TITLE
Cache does not properly fill during startup.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/firehose-to-syslog#28]
One of our environments have > 300 apps, during startup I see this in the log

```
2015/05/06 11:24:32 Error unmarshaling app json: cannot unmarshal number into Go value of type string
```

and after the error is thrown there is only 20 cached apps.

**Comment by simonjohansson** [comment]
Ah, in the go-client
https://github.com/cloudfoundry-community/go-cfclient/blob/master/apps.go#L53

Having a look in my env,
```
$ cf curl "/v2/apps" | head -n 10
{
   "total_results": 382,
   "total_pages": 8,
   "prev_url": null,
   "next_url": "/v2/apps?order-direction=asc&page=2&results-per-page=50",
   "resources": [
      {
         "metadata": {
            "guid": "70857e8f-dafc-4a2b-aa56-3d0523f6252b",
            "url": "/v2/apps/70857e8f-dafc-4a2b-aa56-3d0523f6252b",
```

The client needs to follow next_url if present. Bug in the client, not the implementaton here.

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/go-cfclient/pull/6

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/go-cfclient/pull/6 have been merged into master.

**Comment by shinji62** [comment]
Nice thanks
