### ISSUE TITLE
Missing cf_app_name when app pushed after initial token has expired

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community/firehose-to-syslog#29]
The current implementation of the go-cfclient [fetches a token if there is no is available, but never expires this token](https://github.com/cloudfoundry-community/go-cfclient/blob/b0b0ee06463e8548950ebaefe5834343474efdca/client.go#L167-L172). So when using the client with a long running process you will run into issues.
This issue is fixed in: 
[![go-cfclient#4](https://github-shields.com/github/cloudfoundry-community/go-cfclient/pull/4.svg) ](https://github.com/cloudfoundry-community/go-cfclient/pull/4).

After the above issue is merged the go-cfclient should be updated.

**Comment by simonjohansson** [comment]
Neato!
