### ISSUE TITLE
firehose-to-syslog stopped working with latest go-client and SkipSslValidation.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/firehose-to-syslog#30]
This is just a reference to
https://github.com/cloudfoundry-community/go-cfclient/issues/8

**Comment by shinji62** [comment]
Fixed: https://github.com/cloudfoundry-community/firehose-to-syslog/pull/32

**Comment by simonjohansson** [comment]
Great, thanks!
