### ISSUE TITLE
Use cc /v2/info endpoint for authorization_endpoint and logging_endpoint

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community/firehose-to-syslog#33]
The [hardcoded defaults](https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/main.go#L34-L36) won't work in all environments.
For example our `logging_endpoint` still uses `wss://loggregator.example.com`.

**Comment by simonjohansson** [comment]
Okok!

Lets switch back to

```
--api-endpoint
--uaa-endpoint
--doppler-endpoint
```
?

**Comment by rkoster** [comment]
Yes works for me. About the `loggining_endpoint` just found there are 2 url `doppler` and `loggragator` [both are hardcoded](https://github.com/cloudfoundry/loggregator/blob/aecb94d089dbd24a1ce9730b65b6928d96b606e1/src/trafficcontroller/main.go#L143-L149). But since we only need doppler `--doppler-endpoint` would be the best solution.

**Comment by shinji62** [comment]
I think using api endpoint is enough
```bash
🍣 etourg curl api.run.pivotal.io/v2/info
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"https://login.run.pivotal.io","token_endpoint":"https://uaa.run.pivotal.io","min_cli_version":null,"min_recommended_cli_version":null,"api_version":"2.25.0","logging_endpoint":"wss://loggregator.run.pivotal.io:4443"}
```

**Comment by simonjohansson** [comment]
Ah, thats a good idea!

We could add this into go-cfclient, and add the info in the struct returned from NewClient to subsequently be used to keep the logic out of this project.

That way we only need the api endpoint, user and pwd as @shinji62 sugests.

**Comment by shinji62** [comment]
Already start to work on that but not really working as expected.
Still investigating.

**Comment by simonjohansson** [comment]
@shinji62 let me know if you need a second pair of eyes. :)

**Comment by shinji62** [comment]
First PR: https://github.com/cloudfoundry-community/go-cfclient/pull/12

**Comment by simonjohansson** [comment]
@shinji62 looks good to me :)
Only thing though, should we connect to logging_endpoint as DopplerAddress or make the assumption that doppler will be wss://doppler.domain-from-logging_endpoint:443, if that makes sense?

/v2/info curretly doesnt export this info, but we could make it up ourselves.

**Comment by shinji62** [comment]
I think the only missing part now, it's the possibility to overwrite the doppler address if needed.
login and uaa address should be the right one as it's use by the cf cli.

So I guess I will only let the possibility to overwrite the doppler address.

**Comment by shinji62** [comment]
Everything done there :https://github.com/cloudfoundry-community/firehose-to-syslog/pull/40
