### ISSUE TITLE
Release 1.0.0 stable one

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-community/firehose-to-syslog#42]
Merge to master
Tag.

**Comment by shinji62** [comment]
@simonjohansson Please can you check that.

**Comment by simonjohansson** [comment]
@shinji62 will do!
Ive been a bit busy the last couple of weeks so I have not been able to follow along all the work here, but Ill check it out today. :)

**Comment by simonjohansson** [comment]
@shinji62 
Looked over it all and it looks great! Tried HEAD against 210 and 211 and it work against both versions, dunno about earlier version.

A couple of small that I think we should fix before releasing 1.0.0

* When executing ./firehose-to-syslog without any flags it should show help
* --api-address/--doppler-address: should we switch to api-endpoint/doppler-endpoint, sounds better I think?
* When not specifying --doppler-address I get "Using wss://loggregator.my-domain:443 as doppler endpoint", which does not work. Surely the default doppler-address should be wss://doppler.domain.com:443
* e.Fields["cf_origin"] = "firehose",  e.Fields["event_type"] = e.Type in events/events.go is in AnnotateWithAppData, its not really related to the rest of the stuff in there.

**Comment by shinji62** [comment]
When executing ./firehose-to-syslog without any flags it should show help[1]

==> Agree at least api should be there.


--api-address/--doppler-address: should we switch to api-endpoint/doppler-endpoint, sounds better I think?

==> Yes sounds better I am agree.



When not specifying --doppler-address I get "Using wss://loggregator.my-domain:443 as doppler endpoint", which does not work. Surely the default doppler-address should be wss://doppler.domain.com:443
==> Actually the cloudfoundry api is wrong I think and do not return the right info.

So we should document that I let it in the current form and people should overwrite it if needed.


e.Fields["cf_origin"] = "firehose", e.Fields["event_type"] = e.Type in events/events.go is in AnnotateWithAppData, its not really related to the rest of the stuff in there.
==> I am not sure about this one, it was coming from a PR so maybe we should reconsider it.

Let me know if you agree/dissagree and we can create issues to sort them out, and release ASAP. :)

[1] Altough this would make it slightly more tedious to run against a bosh-lite installation of cf..

**Comment by simonjohansson** [comment]
@shinji62 ok, ill create some cards for the tasks. :)

>  ==> Actually the cloudfoundry api is wrong I think and do not return the right info.

Yep, I have not looked into this, but the doppler address seems to be derived from the api endpoint with the CF client.

```
➜  ~  ls ~/.cf/config.json
ls: cannot access /home/simon/.cf/config.json: No such file or directory
➜  ~  CF_TRACE=true cf login -a https://api.domain.com -u admin -p supersecret -o org -s space | grep doppler
{"access_token":"[PRIVATE DATA HIDDEN]","token_type":"bearer","refresh_token":"[PRIVATE DATA HIDDEN]","expires_in":7199,"scope":"scim.read cloud_controller.admin scim.write cloud_controller.write password.write openid cloud_controller.read doppler.firehose","jti":"683f8326-89fb-4c50-a505-1b77220cb88b"}
➜  ~  cat ~/.cf/config.json | grep doppler
  "DopplerEndPoint": "wss://doppler.domain.com:443",
```

So maybe we should do the same thing in the go-cfclient, just derive the address from the api-address?
http://play.golang.org/p/MMzoy6bhaC
And stick it in https://github.com/cloudfoundry-community/go-cfclient/blob/master/client.go#L22

>  ==> I am not sure about this one, it was coming from a PR so maybe we should reconsider it.

The PR is good I think, thats the only thing I would change. :)

**Comment by simonjohansson** [comment]
@shinji62 
Ive created the following issues and PRs.

#46 
#47 
#48 
#52 

#49 
#50 
#51

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/1.0.0-rc1

Ive created a pre-relese, will try it out in our heavy use Dev env for 24h before releasing a 1.0.0

**Comment by simonjohansson** [comment]
1.0.0-rc2 have been running flawlesly in production for 2 days. Wahey. I will cut a 1.0.0 release.

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/1.0.0

\o/
