### ISSUE TITLE
Migrate to https://github.com/cloudfoundry/sonde-go

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry-community/firehose-to-syslog#43]
We will need to migrate to https://github.com/cloudfoundry/sonde-go as events have been remove from noaa lib.

But sonde-go is not stabilize yet, they remove heartbeat in sonde-go but not in noaa..

**Comment by simonjohansson** [comment]
1.1.0 or 1.0.1? :)

**Comment by shinji62** [comment]
Will say 1.0.1

**Comment by shinji62** [comment]
Will start to work on it quickly..

**Comment by shinji62** [comment]
https://github.com/cloudfoundry-community/firehose-to-syslog/pull/55 done here

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/firehose-to-syslog/releases/tag/1.0.1
