### ISSUE TITLE
Non-debug mode outputs nothing

### ISSUE THREAD

**Issue by chuckbeasley** [cloudfoundry-community/firehose-to-syslog#67]
If --debug is not supplied, it connects to the syslog server. However, no data is ever received at the endpoint.

**Comment by shinji62** [comment]
First time I heard this problem.... 
Please can you give you cf version ? Which IaaS are you using ? 
Can you try using netcat  `nc ` as syslog endpoint ?

**Comment by simonjohansson** [comment]
@chuckbeasley out of interest, what was the issue? :)
