### ISSUE TITLE
Ability to filter logs per application

### ISSUE THREAD

**Issue by stoyanr** [cloudfoundry-community/firehose-to-syslog#73]
At SAP, we are looking at the possibility to install multiple ELK stacks and connect different applications to them. Ideally, we would like to be able to filter firehose logs per application, so that only the logs of certain applications are "ingested" by the firehose ingestor, and all other logs are filtered out. We use [logsearch-for-cloudfoundry](https://github.com/logsearch/logsearch-for-cloudfoundry), which is in turn based on this project.

Filtering logs per application seems not to be possible currently. Have you ever considered this, is this missing intentionally? Would you accept PRs in this direction?

**Comment by shinji62** [comment]
Hi,
Not sure this need to be in firehose-to-syslog.... 
Maybe you can filter at the logstash level.

**Comment by owaism** [comment]
What might be better is the ability to remove logs of a specific application based on a particular condition. For example, if an application goes rogue and starts pumping out thousands of error logs per minute, it would be nice to throttle it or filter it out for a certain amount of time.

If this responsibility is moved to logstash level, there is a big chance that the buffers get overwhelmed and the logstash node can go down. This is the behavior that we are noticing.

**Comment by shinji62** [comment]
Firehose to syslog should be dump as possible, adding to much responsibility is not good.
Even if an application is too noisy, the first buffer to be full will be the firehose one.

Logstash already supporting throttle https://www.elastic.co/guide/en/logstash/current/plugins-filters-throttle.html.
