### ISSUE TITLE
  --version           Show application version.

### ISSUE THREAD

**Issue by smuthuganesh** [cloudfoundry-community/firehose-to-syslog#76]
Hello,

Why I have to provide this flag -api-endpoint to show the application version?

Doesn't work: (which I am expecting to work)
firehose-to-syslog --version
firehose-to-syslog: error: required flag --api-endpoint not provided, try --help

Do work:
firehose-to-syslog --api-endpoint="" --version                                   
1.3.0 - 84c87578

Note1: Anyways, I don't have to provide a valid value to --api-endpoint flag, merely including the flag with empty values works.

Note2: I am aware that I can see the version info from --help-man page
firehose-to-syslog --help-man
.TH firehose-to-syslog 1 1.3.0 - 84c87578 ""

Note3: I do understand from the syntax of firehose-to-syslog, --api-endpoint is mandatory flag.  But, to use the --help flag I don't have to provide empty/valid --api-endpoint flag.  Why not have similar implementation for --version flag?

Thanks

**Comment by shinji62** [comment]
Fix.
