### ISSUE TITLE
Rejected Event Name [Heartbeat]

### ISSUE THREAD

**Issue by smuthuganesh** [cloudfoundry-community/firehose-to-syslog#77]
Hello,

--version 1.3.0 - 84c87578

https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/README.md says
  --events="LogMessage"  
Comma seperated list of events you would like. Valid options are LogMessage, ValueMetric, CounterEvent, Error, ContainerMetric, Heartbeat, HttpStart, HttpStop, HttpStartStop

But, when I tried one of the above listed value "Heartbeat", it throws the following error:
2016/03/18 23:11:15 Error setting up event routing: Rejected Event Name [Heartbeat] - Valid events: HttpStart, HttpStop, HttpStartStop, LogMessage, ValueMetric, CounterEvent, Error, ContainerMetric

Note1: When I looked at the dropsonde protocol documentation, looks like "Heartbeat" has been removed.  I could see rest of events listed there.

Note2: firehose-to-syslog help && "Rejected Event" error message has to be synced.  Also, the order can be matched for easy comparison.  They aren't in same order now:
=HttpStart, HttpStop, HttpStartStop, LogMessage, ValueMetric, CounterEvent, Error, ContainerMetric
=HttpStop, HttpStartStop, LogMessage, ValueMetric, CounterEvent, Error, ContainerMetric, HttpStart

Thanks

**Comment by shinji62** [comment]
@smuthuganesh  That 's just peanut things ..
We don't sync the README everytime , the allows event are generated from the sonde-go protocol which can change.

That's why we have implemented an help command, but I will add a warning into the README
