### ISSUE TITLE
Json events have "time" in seconds precision

### ISSUE THREAD

**Issue by hannayurkevich** [cloudfoundry-community/firehose-to-syslog#79]
Log events that go through 'firehose-to-syslog' tool are wrapped to JSON that includes `"time"` field, e.g.:

`{`
`"cf_app_name":"my-test-app",`
`. . .`
`"msg":"Test message",`
**`"time":"2016-03-28T15:25:20Z"`**
`}`

But why the `time` field has **seconds** precision? I believe that seconds is not enough for the most cases (several log events can happen at the same second and we just don't know their correct order).

Cloud Foundry components' logs usually come with **micro** precision which looks more convenient:
`<14>`**2016-03-28T16:11:03.003172+00:00**` 192.168.111.24 vcap.cloud_controller_ng [job=nfs_z1 index=0]  {. . . }`

Can we make firehose events having **micro** precision as well?

**Comment by shinji62** [comment]
You should refer to the field `timestamp` and not `time`.
The `time`  field is added by the lib logrus, I should be able to change the date format but even that you should use timestamp field.

**Comment by hannayurkevich** [comment]
@shinji62 Using number value for datetime field is not really convenient. To get datetime `timestamp`  value has to be converted to ISO8601 datetime value for each coming event.
Why event datetime can't be included into the JSON and have ISO8601 format with good precision? What is the purpose to provide number `timestamp` instead?

Thank you.

**Comment by shinji62** [comment]
Again there are two things : 
`time` is the field that the nozzle is adding when we fire the logs to the syslog endpoint, no sure we need precision here.
`timestamp` is coming from the firehose itself and we do not touch this field and this field have nano millisecond precision.
