### ISSUE TITLE
If firehose fails or goes down, will log messages be lost during that downtime.

### ISSUE THREAD

**Issue by deepwright** [cloudfoundry-community/firehose-to-syslog#81]
Recently we were seeing Invalid Refresh token  error, which had caused no logs in our log aggregation tool.

When we restarted the firehose app, it refreshed the token and started back sending the logs. So does it mean that we have lost all logs for the apps during this failure or is there a way to recover it.

Can someone please explain this behavior.

**Comment by shinji62** [comment]
Token refresh have been fixed from 1.3.0 releases.

Again this software just format and send logs to syslog endpoint and we do not intent to put any buffer here.

"We have lost all logs for the apps during this failure or is there a way to recover it." 
Cloud Foundry Firehose have a very small buffer, so no way to restore the logs as they do not exist anymore.

If you want real persistence, you can use Kafka or any persistence things to put your logs into.
