### ISSUE TITLE
0 Logs being processed. 

### ISSUE THREAD

**Issue by ahahtyler** [cloudfoundry-community/firehose-to-syslog#82]
I've pushed the firehose-to-syslog nozzle as an application to cloud foundry. However, I've been running into the following error: after sometime,the application stops processing logs. Below is an example log. 

Mon Apr 04 2016 09:03:05 GMT-0400 (Eastern Standard Time) [APP] OUT We have processed 0 events from the firehose at wss://doppler.domain.com:443 over the last 29.9 seconds and 1620115 total events since startup.

We have this app running in a couple different environment with varying volumes of logs being output. In the environment we are seeing the issue, we have around 30,000 logs a minute being output (capturing from 300+ applications). I've increased the number of instances to 6 (with 512 MB of memory) however I'm still seeing the issue. Additionally, the application is only capturing LogMessage events. 

Re-staging the application fixes the issue.

**Comment by shinji62** [comment]
Hi,

Which version are you using ?
30 000/min is not that big 500 /sec if you have 6 nozzle that's mean around 80 logs by nozzle.
I am not sure if the loggregator send in the Round Robin way to all of 6.

Btw when this happen what `cf app youapp` give you ? We use a small on disk database so maybe this DB is full..

Even if you capture only "LogMessage" the nozzle receive all traffic, because the filtering is done on the nozzle level.

**Comment by ahahtyler** [comment]
I'm using version 1.3.1

Looking at the "Log Event Totals" messages, the incoming logs seem to be evenly distributed among the instances. Whenever there is an increase in log volume, all of the events processed by each instance increase, similarly when the volume decreases so do the events processed across all the instances. 

While examining the logs it looks like the issue is related to the instance not responding to a ping in time. 

Tue Apr 05 2016 08:58:53 GMT-0400 (Eastern Standard Time) [APP] ERR [2016-04-05 12:58:53.564120254 +0000 UTC] Exception occurred! Message: Firehose Error! Details: websocket: close 1008 Client did not respond to ping before keep-alive timeout expired.

Tue Apr 05 2016 08:58:53 GMT-0400 (Eastern Standard Time) [APP] OUT We have processed 0 events from the firehose at wss://doppler.domain.com:443 over the last 9.9 seconds and 77575 total events since startup

       state      since                                    cpu     memory               disk                 details
#0   running   2016-04-05 08:33:09 AM   5.3%    23.6M of 512M   14.8M of 512M
**#1   running   2016-04-05 08:33:09 AM   0.0%    25.8M of 512M   14.8M of 512M**
#2   running   2016-04-05 08:33:09 AM   5.0%    21.6M of 512M   14.8M of 512M
#3   running   2016-04-05 08:33:09 AM   14.5%   21.6M of 512M   14.8M of 512M
#4   running   2016-04-05 08:33:09 AM   10.7%   23.6M of 512M   14.8M of 512M
#5   running   2016-04-05 08:33:09 AM   5.0%    19.6M of 512M   14.8M of 512M

After the instances fails to respond to ping before the keep-alive timeout, it's a hit or miss weather it will come back. From the error above, instance 1 started receiving logs again within 10 - 15 minutes. However, I've witnessed it where all of the instances went down and stopped processes logs for 24+ hours.  

Is there a way to increase the keep-alive timeout?

**Comment by shinji62** [comment]
Thanks.
Seems the noaa lib have been updated, so I will updated firehose-to-syslog too.
How many loggregator / doppler to you have ?

By curiousity do you have any network equipment preventing the keep-alive  (firewall)?

**Comment by ahahtyler** [comment]
In each of the cloud foundry foundations we have 2 Doppler and 2 Loggregator VMs (1 vCPU/ 2GB mem). 

There shouldn't be any network equipment preventing the keep-alive. The firehose-to-syslog nozzle is running as an application. From the garden container it's running in to the traffic controller, there's nothing blocking it's path.

**Comment by shinji62** [comment]
Ok, I will try to update the middleware.

**Comment by shinji62** [comment]
Please compile from this branch feature/update_nooa_keepalive using go1.6
```
$godep go build
```

There is a new options 
```
  --fh-keep-alive=25s            Keep Alive duration for the firehose consumer
```


Let me know

**Comment by ahahtyler** [comment]
Built and running. Will let it run over the weekend and see if it still times out.

**Comment by shinji62** [comment]
Still happening ???

**Comment by ahahtyler** [comment]
Sorry for the late reply. Extending the keep alive seems to have done the trick. Thanks for the help!

**Comment by shinji62** [comment]
Ok, I will cut off new release this week.

Thanks

**Comment by chenziliang** [comment]
@shinji62 I am not following why this is a keepalive setting in client since after digging into the source code of server side websocket implementation of client side websocket implementation, it appears the keepalive is initiated by server instead of client ? When server doesn't receive Pong response from client, it will report policy violation and timeout error. 

--fh-keep-alive will be used for websocket client reading packets timeout, it seems not related to keepalive to me.

https://github.com/cloudfoundry-attic/loggregatorlib/blob/master/server/websocket_keepalive.go
