### ISSUE TITLE
events/caching/caching.go:63: multiple-value gcfClient.AppByGuid() in single-value context

### ISSUE THREAD

**Issue by smuthuganesh** [cloudfoundry-community/firehose-to-syslog#87]
Hello,

Should I have to be concerned of this error? How do I fix this?

bash-4.1$ ginkgo -r .
Failed to compile events:

# github.com/cloudfoundry-community/firehose-to-syslog/caching
events/caching/caching.go:63: multiple-value gcfClient.AppByGuid() in single-value context
events/caching/caching.go:81: multiple-value gcfClient.ListApps() in single-value context

Ginkgo ran 1 suite in 4.549190889s
Test Suite Failed
bash-4.1$

**Comment by shinji62** [comment]
Use godep restore first before running gingko ..

**Comment by smuthuganesh** [comment]
Thanks, it worked.

Should this command "godep restore" be part of your README/documentation?

bash-4.1$ ginkgo -r
[1461510543] Events Suite - 8/8 specs â¢â¢â¢â¢â¢â¢â¢â¢ SUCCESS! 616.929Âµs PASS
[1461510543] Extra Fields Suite - 4/4 specs â¢â¢â¢â¢ SUCCESS! 550.688Âµs PASS
[1461510543] Utils Suite - 3/3 specs â¢â¢â¢ SUCCESS! 186.19Âµs PASS

Ginkgo ran 3 suites in 6.843133939s
Test Suite Passed
bash-4.1$

To test and build
# Setup repo
go get github.com/cloudfoundry-community/firehose-to-syslog
cd $GOPATH/src/github.com/cloudfoundry-community/firehose-to-syslog

# Test
ginkgo -r .

# Build binary
godep go build

**Comment by shinji62** [comment]
No need to add this into the documentation, I am working on refactoring the code and the new one will use go vendoring.
