### ISSUE TITLE
non admin user

### ISSUE THREAD

**Issue by smuthuganesh** [cloudfoundry-community/firehose-to-syslog#88]
Hello,

What should I expect if I am using non-admin user?

I won't get admin user to test in my environment and I am not noticing any issues with non-admin user (except it dies @ ~2 hours)

I see your README says, but is 'Admin' user one of the option or the only option?
  --user="admin"      Admin user.
  --password="admin"  Admin password.

Thanks.

**Comment by shinji62** [comment]
You need to get cloudcontroller.write and read right including doppler user.
