### ISSUE TITLE
How do I enable webproxy?

### ISSUE THREAD

**Issue by smuthuganesh** [cloudfoundry-community/firehose-to-syslog#94]
Hello,
I am trying to connect to PCF which is outside my organization.  firehose-to-syslog nozzle is setup in my company VM (RHEL server).  I need webproxy to connect to public URIs.  How do I enable webproxy?
Thanks.

**Comment by shinji62** [comment]
Not supported right now.
I will work on that.
Thanks

**Comment by shinji62** [comment]
Well the fact is this required two change, one in firehose-to-sylog for firehose connection
```
firehose --> proxy --> firehose-to-syslog
```
And inside go-cfclient
```
api,uaa --> proxy --> firehose-to-syslog
```


Btw your proxy should be websocket capable...

**Comment by mrbuk** [comment]
Maybe I am getting something wrong but I think this should work out of the box when setting HTTP_PROXY and HTTPS_PROXY e.g. via

```
export HTTPS_PROXY=http://localhost:8888
export HTTP_PROXY=http://localhost:8888
```

before running `firehose-to-syslog`. `noaa` and `gorilla/websocket` are honoring those settings.

Exporting the two mentioned variables and running `firehose-to-syslog` with `tinyproxy` I see the 
* Events coming through firehose
* tinyproxy saying it established a connection to doppler (see below)

```
INFO      Jul 09 20:19:29 [29935]: Initializing tinyproxy ...
INFO      Jul 09 20:19:29 [29935]: Reloading config file
INFO      Jul 09 20:19:29 [29935]: Setting "Via" header to 'tinyproxy'
WARNING   Jul 09 20:19:29 [29935]: Not running as root, so not changing UID/GID.
INFO      Jul 09 20:19:29 [29935]: Creating child number 1 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 2 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 3 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 4 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 5 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 6 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 7 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 8 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 9 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Creating child number 10 of 10 ...
INFO      Jul 09 20:19:29 [29935]: Finished creating all children.
INFO      Jul 09 20:19:29 [29935]: Setting the various signals.
INFO      Jul 09 20:19:29 [29935]: Starting main loop. Accepting connections.
CONNECT   Jul 09 20:19:35 [29936]: Connect (file descriptor 10): localhost [127.0.0.1]
CONNECT   Jul 09 20:19:35 [29936]: Request (file descriptor 10): CONNECT doppler.xxx:443 HTTP/1.1
INFO      Jul 09 20:19:35 [29936]: No upstream proxy for doppler.xxx
CONNECT   Jul 09 20:19:35 [29936]: Established connection to host "doppler.xxx" using file descriptor 11.
INFO      Jul 09 20:19:35 [29936]: Not sending client headers to remote machine
```

I have tested on OSX with `firehose-to-syslog` 1.3.1, 1.6.0 and current develop branch (1.7.1+)

**Comment by shinji62** [comment]
@mrbuk Websocker is fine.

Does your CF api is behind a proxy too ?
Currently the nozzle connect to websocket and your api which can be http / https.

**Comment by mrbuk** [comment]
@shinji62 You are right. My API was also accessible without the proxy. So it seems that the Proxy config is missing in https://github.com/cloudfoundry-community/go-cfclient/blob/master/client.go#L97, right?

**Comment by shinji62** [comment]
Yes :) so now you understand my comment ...
I will made a PR pretty soon to go-cfclient

**Comment by shinji62** [comment]
Sorry, still need some work.
the GO-cfclient change a lot and I need some time to test the new one.
